name: Build
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -   name: Checkout the code
          uses: actions/checkout@v3

      -   name: Setup JDK 17
          uses: actions/setup-java@v3
          with:
            distribution: 'corretto'
            java-version: 17
            cache: 'gradle'

      -   name: Generate continuous build
          run: ./gradlew assembleContinuous

      -   name: Delete existing tag/release
          uses: dev-drprasad/delete-tag-and-release@v1.0
          with:
            github_token: ${{ secrets.RELEASE_TOKEN }}
            tag_name: continuous

      -   run: sleep 20s

      -   name: Upload binaries to release
          uses: svenstaro/upload-release-action@v2
          with:
            repo_token: ${{ secrets.RELEASE_TOKEN }}
            tag: continuous
            file: app/build/outputs/apk/continuous/app-continuous.apk
            asset_name: io.aayush.relabs_continuous_minAPI21.apk
            prerelease: true
            overwrite: true
            release_name: Continuous Build
